apiVersion: v1
kind: Pod
metadata:
    name: kubia-manual-v2
    labels:
      creation_method: manual
      env: prod
spec:
    containers:
    - image: rann1/kubia
      name: kubia
      ports:
      - containerPort: 8034
        protocol: TCP